# 1 prepare for installation
# psycopg2 error, so psycopg2-binary package instead

- name: Install psycopg2 for Ansible PostgreSQL module
  pip:
    name: psycopg2-binary

# -s /bin/bash, don't use /sbin/nologin because it will let postgresql-setup initdb error
- name: Create PostgreSQL System User
  user:
    name: postgres 
    shell: /bin/bash
    
- name: Create PostgreSQL Databases Directory
  file:
    path: /data/postgresql
    state: directory
    owner: postgres
    group: postgres
    mode: 0700
    
- name: Create dir for PostgreSQL
  file:
    path: '/data/postgresql/{{item}}'
    state: directory
    owner: postgres
    group: postgres
    mode: 0700
  with_items:
    - pgdata
    - config

#2 install by OS family    
- include: "{{ansible_os_family}}.yml"

#3 configure

#4 createdb if need
- name: Create more PostgreSQL user
  become: yes
  become_user: postgres
  postgresql_user:
    name: postgres
    password: '{{postgresql_password}}'
  with_items: "{{docker_applications}}"
  when: docker_applications is not none and docker_applications != ""

- name: Create PostgreSQL extra databases 
  become: yes
  become_user: postgres
  postgresql_db:
    name: "{{ item.name }}"
    encoding: UTF-8
  with_items: "{{ postgresql_databases }}"
  when: (postgresql_databases is defined) and (postgresql_databases != none)

#5 display version and service state of components
- name: Get MongoDB version
  shell: sudo sh -c "psql -V  1>> /data/logs/install_version.txt"

- name: Check PostgreSQL Service
  shell: systemctl status postgresql | grep Active*
  register: check_postgresql_service
  notify: check_postgresql_service
