# 1 prepare for installation
# psycopg2 error, so psycopg2-binary package instead

- name: Install psycopg2 for Ansible PostgreSQL module
  pip:
    name: psycopg2-binary

# -s /bin/bash, don't use /sbin/nologin because it will let postgresql-setup initdb error
- name: Create PostgreSQL System User
  user:
    name: postgres 
    shell: /bin/bash
    
- name: Create PostgreSQL Databases Directory
  file:
    path: /data/postgresql
    state: directory
    owner: postgres
    group: postgres
    mode: 0700
    
- name: Create dir for PostgreSQL
  file:
    path: '/data/postgresql/{{item}}'
    state: directory
    owner: postgres
    group: postgres
    mode: 0700
  with_items:
    - pgdata
    - config

#2 install by OS family    
- include: "{{ansible_os_family}}.yml"

#3 configure

#4 display version and service state of components
- name: Get MongoDB version
  shell: sudo sh -c "psql -V  1>> /data/logs/install_version.txt"

- name: Check PostgreSQL Service
  shell: systemctl status postgresql | grep Active*
  register: check_postgresql_service
  notify: check_postgresql_service
