# Red Hat Enterprise Linux,CentOS,Fedora,Scientific Linux,Oracle Linux
# 9.5.9.6 need convert to 95,96 for some step, e.g yum install postgresql95
- name: Install the repository RPM
  yum:
    name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm

- name: Install PostgreSQL
  yum: 
    name: ["postgresql{{ postgresql_version | regex_replace() }}","postgresql{{ postgresql_version | regex_replace() }}-server"]
    state: latest
    
- name: Initialize databases
  command: /usr/pgsql-{{ postgresql_version }}/bin/postgresql{{ postgresql_version | regex_replace() }}-setup initdb 

- name: Create soft link for PostgreSQL
  shell: |
    ln -sf /usr/lib/systemd/system/postgresql-{{ postgresql_version }}.service  /etc/systemd/system/postgresql.service
  
- name: Start PostgreSQL Service
  service: name=postgresql-{{ postgresql_version }} state=started enabled=yes

- name: Change postgresql password
  become: yes
  become_user: postgres
  postgresql_user:
    name: postgres
    password: '{{postgresql_password}}'
